# Generated by Django 4.0.2 on 2022-02-24 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
