# Generated by Django 4.0.2 on 2022-02-26 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_user_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
